### ISSUE TITLE
the extractor is not working

### ISSUE THREAD

**Issue by qnoox** [github/gemoji#114]
Hello, the extractor is not working so no way to get the actual images.

**Comment by mislav** [comment]
Which version of gemoji library are you using on which version of macOS? Also, how are you invoking the extractor from the command line?

**Comment by qnoox** [comment]
my description was incorrect i'm using the 3.0 version and the issue i'm having is to extract all the images into public folder so they actually show up when using for example :cat: etc.

Have a helper that gets the input and should work to convert but it does not.
<%= emojify(message.content) %>

So the issue is that i'm unable to get the use of alias to show up as emoji.

Things i have tried:
The rake command
exec extract command

Thanks in advance.

**Comment by mislav** [comment]
I can't help you if you don't answer my questions.

1. What version of macOS are you on? You should be running 10.12.2.
2. Which error do you get?

What happens if you try:

```
bundle exec gemoji extract public/images/emoji
```

…and you look inside your `public/images/emoji/` directory? Does it get created? Is it full of images? Or is there an error?

**Comment by qnoox** [comment]
(Sorry Time difference) - I'm Not on MacOS, and the public/images/emoji/ is empty rake command gets error that it does not know emoji task.

**Comment by mislav** [comment]
First of all, there is no rake command since gemoji 3.0. It's only the `gemoji extract` command now.

Second, you have to be on macOS, because the extractor is supposed to extract images from Apple Color Emoji font found on macOS. The command isn't designed for other systems.

We plan to support different emoji sets in the future, but for now, the only emoji set supported is Apple emoji.

**Comment by qnoox** [comment]
Ok Thanks, Please note that like a statement saying only supported on macOS or something would be good, anyhow thank you very much for the help.

**Comment by mislav** [comment]
[There is a statement here](https://github.com/github/gemoji#extract-images), but I agree, the error message from the command could be more helpful. Sorry for the trouble.
