### ISSUE TITLE
Emoji not loading on browser

### ISSUE THREAD

**Issue by nixv2** [github/gemoji#117]
hi! am trying to setup gemoji but when i try to use render the emoji to my view i get an 404 error for the emoji.

am on OS X Yosemite, for what i get the `gemoji extract command` is only for macOS Sierra or later. so am not sure whats wrong. Any help will be appreciated. thanks

**Comment by mislav** [comment]
You probably get a 404 error because the emoji images are not in place. The PNG images are put in place by the `gemoji extract` command, e.g.:

```
gemoji extract public/images/emoji
```

For that command to work, you **have** to have macOS Sierra or later. You can't have any older version of macOS. You will need to find a coworker who is on macOS to perform that command for you, and check new files under `public/images/emoji` to version control.
