### ISSUE TITLE
Add support for empty ballot box and radio button emoji

### ISSUE THREAD

**Issue by JacobDB** [github/gemoji#123]
Forgive me if this isn't the right place for this, but I'd love to see two new emoji added: `:ballot_box_without_check:` and `:radio_button_unchecked:`.

While I was writing some documentation for a project, I wanted to display what settings a user should set with GitHub's emoji. Only problem is, there's no "unchecked" state for either the ballot box or radio button emojis, so I had to resort to using `:white_large_square:` and `:white_circle:`, which don't really look like the ballot box or radio button emojis.

**Comment by mislav** [comment]
Thanks for the suggestion. It doesn't look like to me that Apple's emoji palette (which is what we base our emoji support on) includes the unchecked versions of these emoji. If we wanted to support these, we would have to add them as "custom" emoji and provide an image for them. This is of course doable, and wouldn't even be hard, but the problem would arise because `:ballot_box_with_check:` and `:ballot_box_without_check:` would be rendered with different styles: the former would be native emoji (and rendered using different native emoji representation on different platforms) and the latter would always be a static image, and therefore differ from the first image because of platform differences.

Because of these inconsistencies, I would prefer not to create these custom emoji. What are your thoughts on this?

**Comment by JacobDB** [comment]
Ah, that makes sense. I agree, if there's no native emoji for it then I'll just close this issue.
