### ISSUE TITLE
Add missing writing emoji for my project

### ISSUE THREAD

**Issue by ahtee** [github/gemoji#150]
Was looking to create a project on reusable react components (github.com/copied-components/copied-components) and would like to use the writing hand emoji from Apple ✍️
Would this be possible? Also looking for contributors to get started!

**Comment by mislav** [comment]
Hi, I am not entirely sure what you are asking, but:

1. `writing_hand` is in this library's `db/emoji.json` file, so there's nothing to add;
2. You may not include Apple's emoji images in your projects or anywhere else, since they are copyright by Apple.

You may, however, use the ✍️ _character_ anywhere and let the user's OS render it as an emoji. Or, you can look for iconography from some of the open source emoji sets out there.

Good luck!

**Comment by ahtee** [comment]
@mislav great thank you i realized this later today when trying ✍️ .
