### ISSUE TITLE
Wrong emoji displayed on linux

### ISSUE THREAD

**Issue by ryuukk** [github/gemoji#196]
Hello

I am using Ubuntu 20.10

And emoji's looks very wrong on displayed readme

Example:

https://github.com/ryuukk/zark/blob/main/README.md

![image](https://user-images.githubusercontent.com/44361234/99192281-5aea6d80-2772-11eb-82ed-4194e6cf62ad.png)

![image](https://user-images.githubusercontent.com/44361234/99192298-6f2e6a80-2772-11eb-842b-5f610342cf8c.png)

On VSCode:

![image](https://user-images.githubusercontent.com/44361234/99192303-7a819600-2772-11eb-8d7e-5ea0bc4596ae.png)

This only happen on linux, on windows i get the right emoji

**Comment by ryuukk** [comment]
When i reload the page, i notice the right emoji, but it gets replaced instantly by the weird and WRONG icons on github, and only on github

On both Chrome and Firefox, only github display the wrong one

**Comment by ryuukk** [comment]
More screenshot:
![image](https://user-images.githubusercontent.com/44361234/99192417-0a274480-2773-11eb-88a3-1bdf8190bf6b.png)

**Comment by mislav** [comment]
Hi, I am not sure what in these screenshots do you view as the "right" emoji and which do you think look "wrong". It seems like the checkmark is rendered differently.

The checkmark (✅) emoji is a native emoji, and its rendering is up to the combination of the operating system, web browser, and the font being used. On different platforms, emoji will often look differently. A site like GitHub cannot control how emoji are displayed, and neither can this library called "gemoji" which only serves to parse emoji from content, but doesn't control how emoji are rendered.

As there is no bug here that I can see with this library, I'm going to go ahead and close this. 🙇

**Comment by polarathene** [comment]
Just for added clarification. The README screenshots of rendered markdown content has emoji converted into image/svg content for presentation instead of native emoji. This is intentional for a consistent experience/visual across various systems (which as explained can vary widely), notably to avoid issues with outdated or misconfigured emoji rendering.

Github isn't the only service that does this. Facebook and Twitter are other common platforms that take this approach.

The browser text input fields and non-website screenshots are likely using your system configuration for rendering emoji, this is less stable/reliable, especially on Linux where not all apps are guaranteed to handle emoji in the same way, let alone the differences across distros.
