### ISSUE TITLE
Import Emoji 15.0

### ISSUE THREAD

**Issue by li910802** [github/gemoji#248]
Emoji 15.0 has been released. Any plans?
https://unicode.org/Public/emoji/15.0/
https://emojipedia.org/emoji-15.0/

**Comment by undefinedpersonn** [comment]
What its up for.When you say the plan,what do you mean?

**Comment by sabrican3532** [comment]
> What its up for.When you say the plan,what do you mean?
s***@*******

**Comment by sabrican3532** [comment]
Facebook code

**Comment by Jnuhaque** [comment]
Community help

**Comment by mislav** [comment]
@li910802 Thanks for the suggestion. After Unicode 15 emoji are more widely supported on devices, we will be open to importing the Unicode 15 set into this library. https://github.com/github/gemoji/pull/244#issuecomment-1315647217

**Comment by eliperkins** [comment]
Somewhat related to this discussion, I wonder if making the versions of `gemoji` match the Unicode emoji versions would be a net-positive for consumers and make it more explicit that it will be a "breaking change" (e.g., you'll need to support new emoji images) when going from one version to the next.

For example, if I only have the emoji images for Unicode emoji 14.0, I'd use `gemoji "~>14.0.0"`. Upgrading to `gemoji "~>15.0.0"` would be an explicitly opted-into upgrade.

If my app only supports deployment targets where I _know_ Unicode emoji 15.0 exists, I won't be blocked by `gemoji` updating as well.

I'd love some feedback on this idea!

**Comment by mislav** [comment]
@eliperkins That would make it immediately obvious as to which Unicode version is supported by which version of gemoji, but for other purposes I think it will be detrimental since the new versioning policy would clash with semver practices.

For example:
- `gemoji 15.1.0` supports Unicode 15.1. When we fix some bugs with gemoji, we can release that as `gemoji 15.1.1`, but what if we add some Ruby features unrelated to Unicode? We'd have to tag the next release `gemoji 15.2.1`, which is a misnomer because Unicode 15.2 does not (currently) exist.
- `gemoji 15.1.0` supports Unicode 15.1. Let's say we update gemoji Unicode support to Unicode 16. This is a backwards-compatible change, since all previous emoji are still supported and apps should be safe to upgrade to this new gemoji version, but we still have to tag it `gemoji 16.0.0` (major release = a breaking change in semver) to match the Unicode version.

**Comment by xnousnow** [comment]
Any updates?

**Comment by Olzie-12** [comment]
^^
