### ISSUE TITLE
Skin tones in GitHub flavored markdown

### ISSUE THREAD

**Issue by hlaueriksson** [github/gemoji#256]
Now that `gemoji` supports skin tones, how are they applied in GitHub flavored markdown?

Can skin tones be used with the alias syntax?
For example, how can I apply skin tones to the victory hand with alias `:v:`?

**Comment by mislav** [comment]
Hi, GitHub.com hasn't yet adopted gemoji v4.0, and when it does it's nor guaranteed that it will make use of gemoji support for skin tones.

For comparison, Slack supports syntax like `:+1::skin-tone-6:` that translates to 👍🏿, but in order for GitHub to support that, its Markdown pipeline will have to be expanded with skin tone support and so will the emoji picker that pops up when you start typing `:` in a GitHub textarea. All this will be a lot of work and in the meantime I suggest to everyone that just enter native emoji characters into textareas using your system's default emoji picker instead of waiting for GitHub.com's emoji picker to support skin tones.
